locale/ja/Notepad2.rc

locale ja: misconversion

---

locale/ja/Notepad2.rc

I think I'll use these goto commands.

locale ja: Six Goto commands

---

locale/ja/Notepad2.rc

locale ja: rest of untranslated

---

locale/ko/metapath.rc

Korean Update metapath.rc

---

locale/ko/Notepad2.rc

Korean Update Notepad2.rc

---

scintilla/src/EditView.cxx

Especially for GDI rendering discussed in https://github.com/zufuliu/notepad2/pull/298

Simplify whitespace alpha blending for extreme performance

---

scintilla/lexers/LexBatch.cxx

Locate ending line of subfunctions;
Allow empty label name and comments.
This patch is generated while testing https://github.com/zufuliu/notepad2/pull/348. It's about https://github.com/zufuliu/notepad2/issues/332.
A short test case:
```bat
@echo off
call :Sub
call :Sub1 1 abc
call :Sub2 2 abc
call :Sub3 3 abc
:
echo empty lable name, only comments
exit /b
rem sub procedure, and followed with comments
rem `goto :EOF` as end
rem
:MYFINDSWITCH
%TRACE% [proc %0 %*]
if {%2}=={} (set /a _MTPLIB_T4=1) else (set /a _MTPLIB_T4=%2)
:MYFINDSWITCHLOOP
call :GETSWITCH %_MTPLIB_T4%
if "%RET%"=="" (set RET=0) & (goto :MYFINDSWITCHEND)
if /i "%RET:~1%"=="%1" (set RET=%_MTPLIB_T4%) & (goto :MYFINDSWITCHEND)
set /a _MTPLIB_T4+=1
goto :MYFINDSWITCHLOOP
:MYFINDSWITCHEND
set _MTPLIB_T4=
goto :EOF
rem …
```

LexBatch: improve code folding

---

src/Helpers.c

Clean up SHAddToRecentDocs to obey flagUseSystemMRU.
FileLoad or FileSave will do that.
Fix issue #363.

Improve `Remember Recent Files` performance

---

locale/ja/Notepad2.rc

Update Notepad2.rc Japanese: link

---

locale/it/Notepad2.rc
locale/it/metapath.rc

Good morning,
I have updated the rc files for the Italian localization.
There will probably be some definitions to improve but I would say that as a starting point it is good. ;-)

Italian translation

---

locale/ja/Notepad2.rc

Update Notepad2.rc ja

---

locale/it/Notepad2.rc

Typos fixes and translation improvements

Italian localization update

---

locale/it/Notepad2.rc

Final fix of Italian localization with lexical improvements.
Fix of all label problems in all windows.

Final fix of Italian localization + Fix for issue #492

---

locale/it/Notepad2.rc

Translated a forgotten string. Minor layout corrections and optimisation of the semantics of some translations.

Update Italian translation

---

locale/it/Notepad2.rc

Harmonised the case of menu strings, improved the semantics of some sentences, translated forgotten strings, other minor improvements and corrections.

Revision of Italian translation

---

locale/it/Notepad2.rc

Restored all shortcuts incorrectly deleted during translation. Replaced keys not compatible with the language.

Restored Italian menu and window shortcuts

---

locale/de/Notepad4.rc
locale/de/matepath.rc

Adding German Translation for matepath and Notepad4

German Translation

---

locale/it/Notepad4.rc

Updated new strings in Italian.

Update ITA Notepad4.rc

---

locale/ru/Notepad4(ru).vcxproj
locale/ru/Notepad4(ru).vcxproj.filters
locale/ru/Notepad4.rc
locale/ru/matepath(ru).vcxproj
locale/ru/matepath(ru).vcxproj.filters
locale/ru/matepath.rc

At the moment, the translation is not yet completed, but most of the strings concerning the popular functions have been translated in full.

Add Russian localization

---

locale/it/Notepad4.rc

Update Notepad4.rc IT

---

locale/it/Notepad4.rc
locale/it/matepath.rc

Italian translation of the new strings inserted.

Translation of new strings

---

locale/it/Notepad4.rc

Fixed the meaning/readability of the menu option.

Small correction

---

locale/ru/Notepad4.rc

Significantly updated and fixed Russian translation.

Update Russian Notepad4.rc

---

locale/it/Notepad4.rc

Translated a forgotten string.

Notepad4.rc Update

---

src/Edit.cpp
src/Notepad4.cpp
src/SciCall.h

Keep the same with Scintilla, easier for search.
探究 https://sourceforge.net/p/scintilla/feature-requests/1567/ 时发现的，改一致后便于搜索。

Rename RectangleSelection to RectangularSelection in function names
